server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  mvc:
    view: 
      prefix: /WEB-INF/view
      suffix: .jsp

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_fmp_project?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wtqe2513

  output:
    ansi:
      enabled: always

mybatis:
  mapper-locations:
    - classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org.apache.ibatis: DEBUG
